---
- hosts: all
  remote_user: kathurima
  become: yes
  gather_facts: True

  tasks:
    - name: add universe repository for bionic
      apt_repository: 
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'

    - name: Install base packages
      apt: 
        name: "{{ packages }}"
      vars:
        packages:
          - locales
          - build-essential
          - htop
          - git
          - python3-apt
          - python3-pip
          # - python-certbot-nginx
                  
    - name: Upgrade pip
      pip: name=pip state=latest
      
    - name: Create directory ansible-deploy
      file:
        state: directory
        path: ansible-deploy
    
    - name: Pull project from github
      git:
        repo: 'https://github.com/KathurimaKimathi/Django-Package.git'
        dest: ansible-deploy/
