---
- hosts: all
  remote_user: kathurima
  become: yes
  gather_facts: True

  tasks:
    - name: add repository for certbot
      apt_repository: 
        repo: deb http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main
        state: present
      when: ansible_distribution_release == 'bionic'
      
    - name: Install base packages
      apt: 
        name: "{{ packages }}"
      vars:
        packages:
          - remove certbot
          - python3-certbot-nginx
                    
    - name: Enable UFW
      ufw:
        state: enabled

    - name: Allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow Nginx Full
      ufw:
        rule: allow
        name: Nginx Full

    - name: Obtain SSL certificate
      command: certbot --nginx -d kathurimaportfolio.duckdns.org -d www.kathurimaportfolio.duckdns.org
      become: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: yes