---     #Preferable syntax to start .yml file
- name: Installation          # Name of the task to be performed in the destinaton host
  hosts: all
  #host = All -- Incase you have many servers in your ssh.cfg file
  #hosts: localhost
  become: True        #Makes you an user for the remote host
  tasks: 
    - name: add universe repository for bionic
      apt_repository: 
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'

#------------------------------------------------------------------------------------------------------#
#                                   BASIC SETUP AND INSTALLATION
#------------------------------------------------------------------------------------------------------#
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - locales
        - build-essential
        - python3-apt
        - python3-pip
        - htop
        - python-setuptools
        - git
        - nginx
        state: forcereinstall

    - name: Install pip packages
      pip:
        name: "{{ packages }}"
      vars: 
        packages:
        - model_mommy
        - ansible
        - coverage
        - sentry-sdk
        - certifi
        - django-prometheus
        - gunicorn
        - prometheus-client
        - Django
        - twine
        - fabric3

    - name: Upgrade pip
      pip: name=pip state=latest
      tags:
        - packages

    - name: Create directory
      file:
        state: directory
        path: ansible-deploy

    - name: Pull project from github
      git:
        repo: 'https://github.com/KathurimaKimathi/Django-Package.git'
        dest: ansible-deploy
        update: no
          
    - name: install virtualenv
      pip: 
        name: 
          - virtualenv
    
    - name: install virtualenv
      pip: name=virtualenv
          
    - name: create virtualenv
      command: /usr/local/bin/virtualenv ansible-deploy/dpenv
      
    - name: installing requirements
      pip:
        requirements: /home/kathurima/ansible-deploy/rp-portfolio/requirements.txt
        virtualenv: /home/kathurima/ansible-deploy/dpenv
        virtualenv_python: python3.6

    - name: activate venv and make migrations
      shell: |
        . /home/kathurima/ansible-deploy/dpenv/bin/activate
        python3 /home/kathurima/ansible-deploy/rp-portfolio/manage.py migrate

    # - name: grant user ownership to pollsapp folder
    #   command: "chown sam:www-data /home/sam/muoki/pollsapp"
    #   become: yes
    - name: Recursively change ownership of a directory
      file:
        path: /home/kathurima/ansible-deploy/rp-portfolio
        state: directory
        recurse: yes
        owner: kathurima

#------------------------------------------------------------------------------------------------------#
#                                   NGINX
#------------------------------------------------------------------------------------------------------#
  # tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes

    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes

    - name: copy the nginx config file and restart nginx
      copy:
        src: /home/kathurima/Documents/Work/Personal/Django-Package/rp-portfolio/nginxconfig
        dest: /etc/nginx/sites-available
      become: yes

    - name: create symlink
      file:
        src: /etc/nginx/sites-available/nginxconfig
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes